site_name: homepage docs

# Project information
site_url: https://gethomepage.dev/

# Repository
repo_name: benphelps/homepage
repo_url: https://github.com/benphelps/homepage
edit_uri: https://github.com/benphelps/homepage-docs/tree/main/docs/

nav:
  - 'Home':
    - 'index.md'
  - 'installation':
    - 'installation/index.md'
  - 'configs/index.md'
  - 'services/index.md'
  - 'widgets/index.md'
  - 'more/index.md'

theme:
  name: material
  language: en
  palette:
      - media: "(prefers-color-scheme)"
        toggle:
            icon: material/brightness-auto
            name: Switch to light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: black
        accent: black
        toggle:
            icon: material/brightness-7
            name: Switch to dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: black
        accent: blue
        toggle:
            icon: material/brightness-4
            name: Switch to system preference
  logo: assets/light_squircle@2x.png
  favicon: assets/favicon.ico
  features:
      - navigation.instant
      - content.action.edit
      - navigation.tabs
      - navigation.tabs.sticky
      - search.suggest
      - search.share
      - content.code.copy
      - content.code.select
      - navigation.tracking

extra_css:
  - "stylesheets/extra.css"

extra:
  version:
    provider: mike

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - attr_list
  - md_in_html
  - admonition

plugins:
  - tags
  - typeset
#   - social
  - optimize
  - search:
      pipeline:
        - stemmer
        - stopWordFilter
        - trimmer
